name = "mini-redis"
version = "0.1.0"
defaultTargets = ["mini-redis"]
testDriver = "Test"

[[require]]
scope = "leanprover"
name = "Cli"
version = "git#v4.20.0-rc2"

[[lean_lib]]
name = "MiniRedis"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "mini-redis-client"
root = "Client"

[[lean_exe]]
name = "mini-redis"
root = "Server"
